### ISSUE TITLE
Some icons appear blurred on non-retina displays

### ISSUE THREAD

**Issue by notpushkin** [emroussel/atom-icons#2]
For example, the file icon here:

![image](https://user-images.githubusercontent.com/1298948/74344968-67dec880-4dbe-11ea-85d4-05ebad5c6b09.png)

I don't have Atom installed right now, but you can compare it to GitHub (rendered in latest Chromium) which uses the same icon:

![image](https://user-images.githubusercontent.com/1298948/74345306-f7847700-4dbe-11ea-8853-b08b85cbbeaf.png)

I'll try to work out a PR sometime soon but if you come up with a super easy fix it would be really awesome!

**Comment by emroussel** [comment]
@notpushkin as far as I know, we don't have control over how svgs are rendered, but I might be wrong. What device are you using? Can you also make sure you're testing on the same version of chromium that vs code is using? I would also be curious to know if you're seeing the same issue with different themes or only this one.

Definitely let me know/open a PR if the issue is specific to this theme and you find a way to fix it!

**Comment by DominikSerafin** [comment]
Same problem on Windows 10 with non-retina display at 1920x1080 resolution. Happens in every theme, including Atomize. 

I've created pull request with the fix. 😊
