### ISSUE TITLE
Add archive icons

### ISSUE THREAD

**Issue by novln** [emroussel/atom-icons#7]
Hello,

A quick question on how to contribute to this project.
_By the way, thank you for this extension :+1:._

I would like to add the atom icons for the archive _(ie: zip, tar.gz, etc...)_ and I don't know where to find them.
There is this one available on this website, but it seems different from the one used on atom: https://primer.style/octicons/file-zip-24

Also, what are the technical requirement for the svg file to respect the convention of this folder:
https://github.com/emroussel/atom-icons/tree/main/fileicons/images

Thank you in advance :slightly_smiling_face:

**Comment by emroussel** [comment]
Hi @novln, thanks for being willing to contribute!

Yeah usually the icons on the website you sent match the ones used on Atom, but not always since Atom uses the Octicons font to display the icons. I also wonder if Atom uses an old version of it. You could try to export the svg from the font itself, but I found this repo that seems to have the same icon: https://github.com/shgysk8zer0/octicons-svg/blob/master/file-zip.svg

As for requirements, feel free to follow the existing conventions: add one dark and one light version of the icon in the folder you sent and add the new file type + link to the icons you just added to https://github.com/emroussel/atom-icons/blob/main/fileicons/atom-icon-theme.json. You can also test that your new icon is working by cloning the repo and installing it as an extension to VS Code.

If you're not sure about something, you can always open a PR with the work you currently have and I can help troubleshoot there.
